version: "3.1"

services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_aws"
  sqs:
    image: "softwaremill/elasticmq-native:1.3.9"
    ports:
      - "9324:9324"
      - "9325:9325"
