name: ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}-build
#   cancel-in-progress: true

env:
  
  DJANGO_REPOSITORY: devops_app_backend

jobs:
  django_app_backend:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
         IMAGE_TAG: ${{ github.sha }}
        run: |
         # Build a docker container and push it to ECR 
         docker build -f django_aws/django-ecs-terraform/app/Dockerfile .
         
         #Add tag
         docker tag devops_app_backend:latest 349767822519.dkr.ecr.us-east-1.amazonaws.com/devops_app_backend:latest
         echo "Pushing image to ECR..."
         
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
